apiVersion: v1
kind: Pod
metadata:
  name: nginx02
  labels:
    app: app01
    env: qa
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx03
  labels:
    app: app02
    env: prod
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app03
    env: dev
  name: nginx04
spec:
  containers:
  - name: nginx
    image: nginx