apiVersion: v1
kind: Pod
metadata:
  name: nginx-pods
spec:
  containers:
  - name: nginx01
    image: nginx
    command: ['sh', '-c', 'echo nginx01 > /usr/share/nginx/html/index.html && nginx -g "daemon off;"']
  - name: nginx02
    image: nginx
    command: ['sh', '-c', 'echo nginx02 > /usr/share/nginx/html/index.html && nginx -g "daemon off;"']
