apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-app01
  labels:
    app: rs-app01
spec:
  replicas: 6
  selector:
    matchLabels:
      app: pod-label
  template:
    metadata:
      name: nginx-pods
      labels:
        app: pod-label
    spec:
      containers:
      - name: nginx01
        image: nginx
        command: ['sh', '-c', 'echo contendor01 > /usr/share/nginx/html/index.html && nginx -g "daemon off;"']
      - name: python
        image: python:3.6-alpine
        command: ['sh', '-c', 'echo contenedor02 > index.html && python -m http.server 8082']
