apiVersion: apps/v1
kind: Deployment
metadata:
 #annotations:
   #kubernetes.io/change-cause: "Actualización del Deployment: agregado ports:"
 name: nginx-data
 labels:
   app: data
spec:
 replicas: 3
 selector:
   matchLabels:
     app: data
 template:
   metadata:
     name: nginx-data
     labels:
       app: data
   spec:
     containers:
     - name: nginx01
       image: nginx
       ports:
       - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-nginx-np
  labels:
    app: data
spec:
  type: NodePort
  selector:
    app: data
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30080